// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMigration struct {
	Version string `json:"version"`
}

type User struct {
	ID    int32       `json:"id"`
	Name  string      `json:"name"`
	Email pgtype.Text `json:"email"`
}
